behaviors:
  KuusAgent:
    trainer_type: sac
    hyperparameters:
      learning_rate: 0.0001
      learning_rate_schedule: linear
      batch_size: 1024
      buffer_size: 200000
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 100.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 100.0
    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.995
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 15000000
    time_horizon: 1000
    summary_freq: 51200
    threaded: true
